import type { SubtitleStyle } from "./types";

// Viral subtitle presets. Fonts must exist on the rendering machine.
// The production image ships "Noto Sans Thai" (and the TLWG Thai family), so
// every preset uses an installed Thai-capable font — otherwise libass falls
// back to a Latin face and the chosen style doesn't render as selected.
// Drop extra .ttf files into ./fonts to add more faces, then reference them here.

export const STYLE_PRESETS: SubtitleStyle[] = [
  {
    id: "viral-yellow",
    name: "ไวรัลเหลือง",
    font: "Noto Sans Thai",
    fontSize: 54,
    color: "#FFFFFF",
    highlightColor: "#FFE100",
    outlineColor: "#000000",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: true,
    maxWordsPerCue: 4,
  },
  {
    id: "tiktok-pop",
    name: "TikTok Pop",
    font: "Noto Sans Thai",
    fontSize: 58,
    color: "#FFFFFF",
    highlightColor: "#00E5A0",
    outlineColor: "#11111B",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
    autoEmoji: true,
    autoEmphasis: true,
    emphasisColor: "#00E5A0",
  },
  {
    id: "clean-box",
    name: "กล่องคลีน",
    font: "Noto Sans Thai",
    fontSize: 46,
    color: "#FFFFFF",
    highlightColor: "#FFD166",
    outlineColor: "#000000",
    outlineWidth: 0,
    boxOpacity: 0.65,
    bold: false,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    maxWordsPerCue: 8,
  },
  {
    id: "news-lower",
    name: "ข่าวล่าง",
    font: "Noto Sans Thai",
    fontSize: 40,
    color: "#FFFFFF",
    highlightColor: "#FFFFFF",
    outlineColor: "#1d4ed8",
    outlineWidth: 0,
    boxOpacity: 0.85,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    maxWordsPerCue: 10,
  },
  {
    id: "neon-purple",
    name: "นีออนม่วง",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#F5E0FF",
    highlightColor: "#C084FC",
    outlineColor: "#2e1065",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    maxWordsPerCue: 3,
    autoEmphasis: true,
    emphasisColor: "#C084FC",
  },
  {
    id: "bold-red",
    name: "แดงเด้ง",
    font: "Noto Sans Thai",
    fontSize: 60,
    color: "#FFFFFF",
    highlightColor: "#FF3B3B",
    outlineColor: "#000000",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "clean-white",
    name: "คลีนขาว",
    font: "Noto Sans Thai",
    fontSize: 44,
    color: "#FFFFFF",
    highlightColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 3,
    boxOpacity: 0,
    bold: false,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    maxWordsPerCue: 9,
  },
  {
    id: "dark-box",
    name: "กล่องดำ",
    font: "Noto Sans Thai",
    fontSize: 46,
    color: "#FFFFFF",
    highlightColor: "#FFD166",
    outlineColor: "#000000",
    outlineWidth: 0,
    boxOpacity: 0.8,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    maxWordsPerCue: 8,
  },
  {
    id: "sunset",
    name: "พระอาทิตย์ตก",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#FF8A3D",
    outlineColor: "#3B0764",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    emphasisColor: "#FF8A3D",
    autoEmphasis: true,
    maxWordsPerCue: 3,
  },
  {
    id: "ocean",
    name: "ทะเล",
    font: "Noto Sans Thai",
    fontSize: 54,
    color: "#FFFFFF",
    highlightColor: "#38BDF8",
    outlineColor: "#0C4A6E",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    maxWordsPerCue: 3,
  },
  {
    id: "bubblegum",
    name: "หมากฝรั่ง",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#FF6FB5",
    outlineColor: "#500724",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: true,
    emphasisColor: "#FF6FB5",
    autoEmphasis: true,
    maxWordsPerCue: 4,
    autoEmoji: true,
  },
  {
    id: "gold-lux",
    name: "ทองหรู",
    font: "Noto Sans Thai",
    fontSize: 52,
    color: "#FFFFFF",
    highlightColor: "#FFD700",
    outlineColor: "#1C1917",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    emphasisColor: "#FFD700",
    autoEmphasis: true,
    maxWordsPerCue: 7,
  },
  {
    id: "mint",
    name: "มินต์",
    font: "Noto Sans Thai",
    fontSize: 50,
    color: "#FFFFFF",
    highlightColor: "#34D399",
    outlineColor: "#064E3B",
    outlineWidth: 4,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    maxWordsPerCue: 3,
  },
  {
    id: "podcast-lower",
    name: "พอดแคสต์ล่าง",
    font: "Noto Sans Thai",
    fontSize: 40,
    color: "#FFFFFF",
    highlightColor: "#A78BFA",
    outlineColor: "#4C1D95",
    outlineWidth: 0,
    boxOpacity: 0.7,
    bold: true,
    uppercase: false,
    position: "bottom",
    wordHighlight: false,
    maxWordsPerCue: 10,
  },
  {
    id: "hormozi-box",
    name: "กล่องดำ คำเด้ง",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#00E676",
    outlineColor: "#000000",
    outlineWidth: 3,
    boxOpacity: 0.85,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "yellow-box",
    name: "เหลืองกล่องดำ",
    font: "Noto Sans Thai",
    fontSize: 54,
    color: "#FFE100",
    highlightColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 2,
    boxOpacity: 0.85,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "orange-fire",
    name: "ส้มไฟ",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#FF6A00",
    outlineColor: "#1A0E00",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "hot-pink",
    name: "ชมพูนีออน",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#FF2D86",
    outlineColor: "#2A0014",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "cyber-cyan",
    name: "ฟ้าไซเบอร์",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#00E5FF",
    outlineColor: "#001A1F",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "purple-box",
    name: "ม่วงกล่อง",
    font: "Noto Sans Thai",
    fontSize: 54,
    color: "#FFFFFF",
    highlightColor: "#C77DFF",
    outlineColor: "#1A0033",
    outlineWidth: 2,
    boxOpacity: 0.8,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
  {
    id: "red-punch",
    name: "แดงใหญ่เด้ง",
    font: "Noto Sans Thai",
    fontSize: 62,
    color: "#FFFFFF",
    highlightColor: "#FF1744",
    outlineColor: "#1A0006",
    outlineWidth: 6,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 2,
  },
  {
    id: "lime-zest",
    name: "เขียวเลม่อน",
    font: "Noto Sans Thai",
    fontSize: 56,
    color: "#FFFFFF",
    highlightColor: "#C6FF00",
    outlineColor: "#0F1A00",
    outlineWidth: 5,
    boxOpacity: 0,
    bold: true,
    uppercase: false,
    position: "center",
    wordHighlight: true,
    wordPop: true,
    maxWordsPerCue: 3,
  },
];

export function getStyle(id: string): SubtitleStyle {
  return STYLE_PRESETS.find((s) => s.id === id) ?? STYLE_PRESETS[0];
}
